# Generated by Django 5.0.3 on 2024-04-02 20:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('n_questions', models.PositiveIntegerField()),
                ('n_attempts', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1)),
                ('quality_of_answer', models.PositiveIntegerField(choices=[(0, 'Blackout'), (1, 'Attempted, little progress.'), (2, 'Attempted, close but needed more.'), (3, 'Correct, but with a lot of difficulty.'), (4, 'Correct, but with some syntax errors.'), (5, 'Correct, with no difficulities.')])),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.category')),
            ],
        ),
    ]
